#pragma once

#define CUDAO_VERSION_MAJOR 0
#define CUDAO_VERSION_MINOR 1
#define CUDAO_VERSION_PATCH 0

#define CUDAO_VERSION \
    (CUDAO_VERSION_MAJOR * 10000 + CUDAO_VERSION_MINOR * 100 + CUDAO_VERSION_PATCH)
