from __future__ import annotations

import argparse
import pathlib
import re
import sys
from datetime import datetime, timezone

LOCAL_INCLUDE_RE = re.compile(
    r'^\s*#\s*include\s*"([^"]+)"\s*(?://.*)?$'
)
PRAGMA_ONCE_RE = re.compile(
    r'^\s*#\s*pragma\s+once\b'
)


def is_under(path: pathlib.Path, root: pathlib.Path) -> bool:
    path = path.resolve()
    root = root.resolve()
    return path == root or root in path.parents


def resolve_local_include(
        include_name: str,
        current_file: pathlib.Path,
        include_root: pathlib.Path,
) -> pathlib.Path | None:
    candidates = [
        current_file.parent / include_name,
        include_root / include_name,
        ]

    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved.is_file() and is_under(resolved, include_root):
            return resolved

    return None


def append_file(
        path: pathlib.Path,
        include_root: pathlib.Path,
        output: list[str],
        visited: set[pathlib.Path],
        stack: list[pathlib.Path],
) -> None:
    path = path.resolve()

    if path in visited:
        return

    if path in stack:
        cycle = " -> ".join(str(p.relative_to(include_root)) for p in stack + [path])
        raise RuntimeError(f"cyclic include detected: {cycle}")

    stack.append(path)
    rel = path.relative_to(include_root)

    output.append("\n")
    output.append(f"// ===== begin {rel.as_posix()} =====\n")

    text = path.read_text(encoding="utf-8")
    for line in text.splitlines(keepends=True):
        if PRAGMA_ONCE_RE.match(line):
            continue

        match = LOCAL_INCLUDE_RE.match(line)
        if match:
            include_name = match.group(1)
            resolved = resolve_local_include(include_name, path, include_root)
            if resolved is None:
                raise RuntimeError(
                    f'unresolved local include "{include_name}" in {rel.as_posix()}'
                )

            append_file(resolved, include_root, output, visited, stack)
            continue

        output.append(line)

    if output and not output[-1].endswith("\n"):
        output.append("\n")

    output.append(f"// ===== end {rel.as_posix()} =====\n")

    stack.pop()
    visited.add(path)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the single-header cuDAO.cuh from modular headers."
    )
    parser.add_argument(
        "--root",
        required=True,
        help="Project include root, usually <repo>/include.",
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Aggregation header to expand, usually <repo>/include/cuDAO.cuh.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Generated single header path.",
    )

    args = parser.parse_args()

    include_root = pathlib.Path(args.root).resolve()
    input_header = pathlib.Path(args.input).resolve()
    output_header = pathlib.Path(args.output).resolve()

    if not input_header.is_file():
        raise RuntimeError(f"input header not found: {input_header}")

    if not is_under(input_header, include_root):
        raise RuntimeError("input header must be under include root")

    body: list[str] = []
    append_file(
        input_header,
        include_root,
        body,
        visited=set(),
        stack=[],
    )

    generated = []
    generated.append("// This file is generated by tools/amalgamate.py. Do not edit directly.\n")
    generated.append("// Source: include/cuDAO.cuh\n")
    generated.append(
        f"// Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
    )
    generated.append("#pragma once\n")
    generated.extend(body)

    output_header.parent.mkdir(parents=True, exist_ok=True)
    output_header.write_text("".join(generated), encoding="utf-8")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"amalgamate.py: error: {exc}", file=sys.stderr)
        raise SystemExit(1)